#include<iostream>
using namespace std;
int main()
{
    cout << "C Language Basic Syntax Rules: \n ";
    cout << "1. Lowercase letters are significant \n ";
    cout << "2. main is where program execution begins \n ";
    cout << "3. Opening and closing braces enclose program statements in a routine \n ";
    cout << "4. All program statements must be terminated by a semicolon \n ";

    return 0;
}